title = "Susan's Math Games"
#baseURL = "https://pimsmath.github.io/susansmathgames/"
languageCode = "en-us"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Susan's Math Games"
    weight = 1
    contentDir = "content/en"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  custom_css = ["css/local.css"]
  favicon = ""
  site_logo = "/images/logo.png"
  description = "Encouraging the development of mathematical thinking through play&#8230;"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-blue"
  featured_image = "/images/kbbg.jpeg"
  recent_posts_number = 4 

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    pre = "<i class='fa fa-heart'></i>"
    url = "/about/"
    weight = 100

  [[menu.main]]
    name = "For teachers"
    pre = "<i class='fa fa-road'></i>"
    url = "/for-teachers/"
    weight = -90
  
  [[menu.main]]
    name = "Other resources"
    pre = "<i class='fa fa-road'></i>"
    url = "/other-resources/"
    weight = -80
